/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BusinessAddress : Serializer for BusinessAddress model. Used for merchant and shipping addresses.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BusinessAddress {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "postal_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<Option<String>>,
    #[serde(rename = "city_name")]
    pub city_name: String,
    #[serde(rename = "state_name")]
    pub state_name: String,
    #[serde(rename = "district_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub district_id: Option<Option<i32>>,
    #[serde(rename = "district_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub district_name: Option<Option<String>>,
    #[serde(rename = "longitude", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<Option<String>>,
    #[serde(rename = "latitude", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<Option<String>>,
    #[serde(rename = "building_number", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub building_number: Option<Option<String>>,
    #[serde(rename = "unit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unit: Option<Option<String>>,
    #[serde(rename = "receiver_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub receiver_name: Option<Option<String>>,
    #[serde(rename = "receiver_phone", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub receiver_phone: Option<Option<String>>,
    #[serde(rename = "is_accurate", skip_serializing_if = "Option::is_none")]
    pub is_accurate: Option<bool>,
    #[serde(rename = "is_active", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at")]
    pub modified_at: String,
}

impl BusinessAddress {
    /// Serializer for BusinessAddress model. Used for merchant and shipping addresses.
    pub fn new(id: i32, address: String, city_name: String, state_name: String, created_at: String, modified_at: String) -> BusinessAddress {
        BusinessAddress {
            id,
            address,
            postal_code: None,
            city_name,
            state_name,
            district_id: None,
            district_name: None,
            longitude: None,
            latitude: None,
            building_number: None,
            unit: None,
            receiver_name: None,
            receiver_phone: None,
            is_accurate: None,
            is_active: None,
            created_at,
            modified_at,
        }
    }
}

