/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeliveryTimeRangeDisplay {
    #[serde(rename = "min_date")]
    pub min_date: String,
    #[serde(rename = "max_date")]
    pub max_date: String,
}

impl DeliveryTimeRangeDisplay {
    pub fn new(min_date: String, max_date: String) -> DeliveryTimeRangeDisplay {
        DeliveryTimeRangeDisplay {
            min_date,
            max_date,
        }
    }
}

