/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ErrorEnum : * `User is not authenticated.` - کاربر تأیید هویت نشده است. * `Order not found.` - Order not found. * `Order is not in a state where shipping can be selected.` - سفارش در وضعیتی نیست که بتوان روش ارسال را انتخاب کرد. * `Order is not in a state where packing can be selected.` - سفارش در وضعیتی نیست که بتوان بسته‌بندی را انتخاب کرد. * `Failed to initiate refund. Please try again later.` - عملیات بازپرداخت ناموفق بود. لطفاً بعداً دوباره امتحان کنید. * `Order is expired or cancelled.` - سفارش منقضی‌شده یا لغو‌شده است. * `Invalid request origin.` - Invalid request origin. * `Digi Express shipping method not found.` - روش ارسال دیجی اکسپرس یافت نشد. * `Order address not found.` - آدرس سفارش یافت نشد. * `Failed to fetch Digi Express shipping time window options.` - دریافت گزینه‌های بازه زمانی ارسال دیجی اکسپرس ناموفق بود. * `Address ID not found.` - Address ID not found. * `Failed to cancel shipment.` - خطا در کنسل کردن مرسوله. * `Failed to cancel shipment in third party service.` - خطا در کنسل کردن مرسوله از سمت سرویس خارجی. * `Shipment not found.` - Shipment not found. * `Selected shipping method is not eligible for cancellation.` - Selected shipping method is not eligible for cancellation. * `DigiExpress shipment is not in cancelable in this state` - مرسوله دیجی‌اکسپرس در این وضعیت قابل کنسل شدن نیست. * `DigiExpress shipment is not in reviveable in this state` - مرسوله دیجی‌اکسپرس در این وضعیت قابل ارسال مجدد نیست. * `Failed to revive shipment in third party service.` - Failed to revive shipment in third party service. * `Selected shipping method is not eligible for revival.` - Selected shipping method is not eligible for revival.
/// * `User is not authenticated.` - کاربر تأیید هویت نشده است. * `Order not found.` - Order not found. * `Order is not in a state where shipping can be selected.` - سفارش در وضعیتی نیست که بتوان روش ارسال را انتخاب کرد. * `Order is not in a state where packing can be selected.` - سفارش در وضعیتی نیست که بتوان بسته‌بندی را انتخاب کرد. * `Failed to initiate refund. Please try again later.` - عملیات بازپرداخت ناموفق بود. لطفاً بعداً دوباره امتحان کنید. * `Order is expired or cancelled.` - سفارش منقضی‌شده یا لغو‌شده است. * `Invalid request origin.` - Invalid request origin. * `Digi Express shipping method not found.` - روش ارسال دیجی اکسپرس یافت نشد. * `Order address not found.` - آدرس سفارش یافت نشد. * `Failed to fetch Digi Express shipping time window options.` - دریافت گزینه‌های بازه زمانی ارسال دیجی اکسپرس ناموفق بود. * `Address ID not found.` - Address ID not found. * `Failed to cancel shipment.` - خطا در کنسل کردن مرسوله. * `Failed to cancel shipment in third party service.` - خطا در کنسل کردن مرسوله از سمت سرویس خارجی. * `Shipment not found.` - Shipment not found. * `Selected shipping method is not eligible for cancellation.` - Selected shipping method is not eligible for cancellation. * `DigiExpress shipment is not in cancelable in this state` - مرسوله دیجی‌اکسپرس در این وضعیت قابل کنسل شدن نیست. * `DigiExpress shipment is not in reviveable in this state` - مرسوله دیجی‌اکسپرس در این وضعیت قابل ارسال مجدد نیست. * `Failed to revive shipment in third party service.` - Failed to revive shipment in third party service. * `Selected shipping method is not eligible for revival.` - Selected shipping method is not eligible for revival.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ErrorEnum {
    #[serde(rename = "User is not authenticated.")]
    UserIsNotAuthenticated,
    #[serde(rename = "Order not found.")]
    OrderNotFound,
    #[serde(rename = "Order is not in a state where shipping can be selected.")]
    OrderIsNotInAStateWhereShippingCanBeSelected,
    #[serde(rename = "Order is not in a state where packing can be selected.")]
    OrderIsNotInAStateWherePackingCanBeSelected,
    #[serde(rename = "Failed to initiate refund. Please try again later.")]
    FailedToInitiateRefundPleaseTryAgainLater,
    #[serde(rename = "Order is expired or cancelled.")]
    OrderIsExpiredOrCancelled,
    #[serde(rename = "Invalid request origin.")]
    InvalidRequestOrigin,
    #[serde(rename = "Digi Express shipping method not found.")]
    DigiExpressShippingMethodNotFound,
    #[serde(rename = "Order address not found.")]
    OrderAddressNotFound,
    #[serde(rename = "Failed to fetch Digi Express shipping time window options.")]
    FailedToFetchDigiExpressShippingTimeWindowOptions,
    #[serde(rename = "Address ID not found.")]
    AddressIdNotFound,
    #[serde(rename = "Failed to cancel shipment.")]
    FailedToCancelShipment,
    #[serde(rename = "Failed to cancel shipment in third party service.")]
    FailedToCancelShipmentInThirdPartyService,
    #[serde(rename = "Shipment not found.")]
    ShipmentNotFound,
    #[serde(rename = "Selected shipping method is not eligible for cancellation.")]
    SelectedShippingMethodIsNotEligibleForCancellation,
    #[serde(rename = "DigiExpress shipment is not in cancelable in this state")]
    DigiExpressShipmentIsNotInCancelableInThisState,
    #[serde(rename = "DigiExpress shipment is not in reviveable in this state")]
    DigiExpressShipmentIsNotInReviveableInThisState,
    #[serde(rename = "Failed to revive shipment in third party service.")]
    FailedToReviveShipmentInThirdPartyService,
    #[serde(rename = "Selected shipping method is not eligible for revival.")]
    SelectedShippingMethodIsNotEligibleForRevival,

}

impl std::fmt::Display for ErrorEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UserIsNotAuthenticated => write!(f, "User is not authenticated."),
            Self::OrderNotFound => write!(f, "Order not found."),
            Self::OrderIsNotInAStateWhereShippingCanBeSelected => write!(f, "Order is not in a state where shipping can be selected."),
            Self::OrderIsNotInAStateWherePackingCanBeSelected => write!(f, "Order is not in a state where packing can be selected."),
            Self::FailedToInitiateRefundPleaseTryAgainLater => write!(f, "Failed to initiate refund. Please try again later."),
            Self::OrderIsExpiredOrCancelled => write!(f, "Order is expired or cancelled."),
            Self::InvalidRequestOrigin => write!(f, "Invalid request origin."),
            Self::DigiExpressShippingMethodNotFound => write!(f, "Digi Express shipping method not found."),
            Self::OrderAddressNotFound => write!(f, "Order address not found."),
            Self::FailedToFetchDigiExpressShippingTimeWindowOptions => write!(f, "Failed to fetch Digi Express shipping time window options."),
            Self::AddressIdNotFound => write!(f, "Address ID not found."),
            Self::FailedToCancelShipment => write!(f, "Failed to cancel shipment."),
            Self::FailedToCancelShipmentInThirdPartyService => write!(f, "Failed to cancel shipment in third party service."),
            Self::ShipmentNotFound => write!(f, "Shipment not found."),
            Self::SelectedShippingMethodIsNotEligibleForCancellation => write!(f, "Selected shipping method is not eligible for cancellation."),
            Self::DigiExpressShipmentIsNotInCancelableInThisState => write!(f, "DigiExpress shipment is not in cancelable in this state"),
            Self::DigiExpressShipmentIsNotInReviveableInThisState => write!(f, "DigiExpress shipment is not in reviveable in this state"),
            Self::FailedToReviveShipmentInThirdPartyService => write!(f, "Failed to revive shipment in third party service."),
            Self::SelectedShippingMethodIsNotEligibleForRevival => write!(f, "Selected shipping method is not eligible for revival."),
        }
    }
}

impl Default for ErrorEnum {
    fn default() -> ErrorEnum {
        Self::UserIsNotAuthenticated
    }
}

