/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// GatewayTypeEnum : * `1` - آنلاین * `2` - BNPL (الان بخر، بعداً پرداخت کن) * `3` - اعتباری * `4` - کیف پول دیجی‌پی * `5` - اقساط پیش‌فرض
/// * `1` - آنلاین * `2` - BNPL (الان بخر، بعداً پرداخت کن) * `3` - اعتباری * `4` - کیف پول دیجی‌پی * `5` - اقساط پیش‌فرض
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum GatewayTypeEnum {
    Variant1 = 1,
    Variant2 = 2,
    Variant3 = 3,
    Variant4 = 4,
    Variant5 = 5,

}

impl std::fmt::Display for GatewayTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::Variant1 => "1",
            Self::Variant2 => "2",
            Self::Variant3 => "3",
            Self::Variant4 => "4",
            Self::Variant5 => "5",
        })
    }
}
impl Default for GatewayTypeEnum {
    fn default() -> GatewayTypeEnum {
        Self::Variant1
    }
}

