/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MerchantOrderRefundResponse {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "order_uuid")]
    pub order_uuid: uuid::Uuid,
    #[serde(rename = "status")]
    pub status: models::OrderStatusEnum,
    #[serde(rename = "status_display")]
    pub status_display: String,
    #[serde(rename = "refund_reason")]
    pub refund_reason: String,
}

impl MerchantOrderRefundResponse {
    pub fn new(message: String, order_uuid: uuid::Uuid, status: models::OrderStatusEnum, status_display: String, refund_reason: String) -> MerchantOrderRefundResponse {
        MerchantOrderRefundResponse {
            message,
            order_uuid,
            status,
            status_display,
            refund_reason,
        }
    }
}

