/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MerchantPaidOrderList : Serializer for manager view listing PAID_BY_USER orders
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MerchantPaidOrderList {
    #[serde(rename = "order_uuid")]
    pub order_uuid: uuid::Uuid,
    /// شناسه منحصر به فرد سفارش در سیستم فروشنده
    #[serde(rename = "merchant_order_id")]
    pub merchant_order_id: String,
    /// شناسه منحصر به فرد فروشنده برای تأیید سفارش
    #[serde(rename = "merchant_unique_id")]
    pub merchant_unique_id: String,
    #[serde(rename = "paid_at", deserialize_with = "Option::deserialize")]
    pub paid_at: Option<String>,
    #[serde(rename = "refunds_at", deserialize_with = "Option::deserialize")]
    pub refunds_at: Option<String>,
}

impl MerchantPaidOrderList {
    /// Serializer for manager view listing PAID_BY_USER orders
    pub fn new(order_uuid: uuid::Uuid, merchant_order_id: String, merchant_unique_id: String, paid_at: Option<String>, refunds_at: Option<String>) -> MerchantPaidOrderList {
        MerchantPaidOrderList {
            order_uuid,
            merchant_order_id,
            merchant_unique_id,
            paid_at,
            refunds_at,
        }
    }
}

