/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Option {
    /// نوع ویژگی محصول: رنگ، سایز، گارانتی، وزن یا سایر  * `color` - رنگ * `size` - اندازه * `warranty` - گارانتی * `weight` - وزن * `other` - سایر
    #[serde(rename = "type_name")]
    pub type_name: models::TypeNameEnum,
    /// نام ویژگی (مثلاً 'قرمز' برای رنگ قرمز، 'XL' برای سایز)
    #[serde(rename = "name")]
    pub name: String,
    /// مقدار ویژگی (مثلاً '#FF0000' برای کد رنگ یا مقدار دیگر)
    #[serde(rename = "value")]
    pub value: String,
    /// اگر نوع ویژگی رنگ است درست است، وگرنه غلط
    #[serde(rename = "is_color", skip_serializing_if = "Option::is_none")]
    pub is_color: Option<bool>,
}

impl Option {
    pub fn new(type_name: models::TypeNameEnum, name: String, value: String) -> Option {
        Option {
            type_name,
            name,
            value,
            is_color: None,
        }
    }
}

