/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderCreateResponse {
    #[serde(rename = "order_start_url")]
    pub order_start_url: String,
    #[serde(rename = "order_uuid")]
    pub order_uuid: uuid::Uuid,
}

impl OrderCreateResponse {
    pub fn new(order_start_url: String, order_uuid: uuid::Uuid) -> OrderCreateResponse {
        OrderCreateResponse {
            order_start_url,
            order_uuid,
        }
    }
}

