/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderCreate {
    /// شناسه منحصر به فرد این سفارش در سیستم فروشنده
    #[serde(rename = "merchant_order_id")]
    pub merchant_order_id: String,
    /// شناسه منحصر به فرد برای تأیید اصالت سفارش
    #[serde(rename = "merchant_unique_id")]
    pub merchant_unique_id: String,
    /// مجموع قیمت‌های اولیه تمام کالاها بدون تخفیف (به تومان)
    #[serde(rename = "main_amount", skip_serializing_if = "Option::is_none")]
    pub main_amount: Option<i32>,
    /// مبلغ نهایی: مبلغ_اصلی - مبلغ_تخفیف + مبلغ_مالیات (به تومان)
    #[serde(rename = "final_amount", skip_serializing_if = "Option::is_none")]
    pub final_amount: Option<i32>,
    /// مبلغ کل پرداخت شده توسط کاربر: مبلغ_نهایی + هزینه_ارسال (به تومان)
    #[serde(rename = "total_paid_amount", skip_serializing_if = "Option::is_none")]
    pub total_paid_amount: Option<i32>,
    /// مبلغ کل تخفیف برای تمام سفارش (به تومان)
    #[serde(rename = "discount_amount", skip_serializing_if = "Option::is_none")]
    pub discount_amount: Option<i32>,
    /// مبلغ کل مالیات برای تمام سفارش (به تومان)
    #[serde(rename = "tax_amount", skip_serializing_if = "Option::is_none")]
    pub tax_amount: Option<i32>,
    /// هزینه ارسال برای سفارش (به تومان)
    #[serde(rename = "shipping_amount", skip_serializing_if = "Option::is_none")]
    pub shipping_amount: Option<i32>,
    /// مبلغ تخفیف باشگاه مشتریان/پاداش (به تومان)
    #[serde(rename = "loyalty_amount", skip_serializing_if = "Option::is_none")]
    pub loyalty_amount: Option<i32>,
    /// آدرس وب‌هوک برای دریافت اطلاع رسانی وضعیت پرداخت
    #[serde(rename = "callback_url")]
    pub callback_url: String,
    #[serde(rename = "destination_address", deserialize_with = "Option::deserialize")]
    pub destination_address: Option<serde_json::Value>,
    #[serde(rename = "items")]
    pub items: Vec<models::OrderItemCreate>,
    /// مقدار توسط سیستم جایگذاری می شود
    #[serde(rename = "merchant", skip_serializing_if = "Option::is_none")]
    pub merchant: Option<i32>,
    /// مقدار توسط سیستم جایگذاری می شود
    #[serde(rename = "source_address", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub source_address: Option<Option<serde_json::Value>>,
    #[serde(rename = "user", deserialize_with = "Option::deserialize")]
    pub user: Option<i32>,
    /// مهلت پرداخت (به عنوان Unix timestamp) قبل از اتمام سفارش
    #[serde(rename = "reservation_expired_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reservation_expired_at: Option<Option<i32>>,
    /// کد مرجع یکتا برای پیگیری سفارش مشتری (قالب: BD-XXXXXXXX)
    #[serde(rename = "reference_code")]
    pub reference_code: String,
    /// Preparation time for the order (in days)
    #[serde(rename = "preparation_time", skip_serializing_if = "Option::is_none")]
    pub preparation_time: Option<i32>,
    /// Total Weight of the order (in grams)
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<f64>,
}

impl OrderCreate {
    pub fn new(merchant_order_id: String, merchant_unique_id: String, callback_url: String, destination_address: Option<serde_json::Value>, items: Vec<models::OrderItemCreate>, user: Option<i32>, reference_code: String) -> OrderCreate {
        OrderCreate {
            merchant_order_id,
            merchant_unique_id,
            main_amount: None,
            final_amount: None,
            total_paid_amount: None,
            discount_amount: None,
            tax_amount: None,
            shipping_amount: None,
            loyalty_amount: None,
            callback_url,
            destination_address,
            items,
            merchant: None,
            source_address: None,
            user,
            reservation_expired_at: None,
            reference_code,
            preparation_time: None,
            weight: None,
        }
    }
}

