/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderItemCreate {
    /// نام کامل محصول شامل تمام مشخصات
    #[serde(rename = "name")]
    pub name: String,
    /// قیمت اولیه برای هر واحد بدون تخفیف (به تومان)
    #[serde(rename = "primary_amount", skip_serializing_if = "Option::is_none")]
    pub primary_amount: Option<i32>,
    /// قیمت نهایی برای تمام واحدها بعد از تخفیف (به تومان)
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<i32>,
    /// تعداد واحدهای این کالا در سفارش
    #[serde(rename = "count")]
    pub count: i32,
    /// مبلغ کل تخفیف برای این کالا (به تومان)
    #[serde(rename = "discount_amount", skip_serializing_if = "Option::is_none")]
    pub discount_amount: Option<i32>,
    /// مبلغ کل مالیات برای این کالا (به تومان)
    #[serde(rename = "tax_amount", skip_serializing_if = "Option::is_none")]
    pub tax_amount: Option<i32>,
    /// آدرس تصویر محصول
    #[serde(rename = "image_link", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image_link: Option<Option<String>>,
    #[serde(rename = "options")]
    pub options: Vec<models::Option>,
    /// Preparation time for the item (in days)
    #[serde(rename = "preparation_time", skip_serializing_if = "Option::is_none")]
    pub preparation_time: Option<i32>,
    /// Weight of the item (in grams)
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<f64>,
}

impl OrderItemCreate {
    pub fn new(name: String, count: i32, options: Vec<models::Option>) -> OrderItemCreate {
        OrderItemCreate {
            name,
            primary_amount: None,
            amount: None,
            count,
            discount_amount: None,
            tax_amount: None,
            image_link: None,
            options,
            preparation_time: None,
            weight: None,
        }
    }
}

