/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderDetail {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "order_uuid")]
    pub order_uuid: uuid::Uuid,
    /// Unix timestamp تا زمانی که سفارش برای پرداخت رزرو شده است
    #[serde(rename = "reservation_expired_at", deserialize_with = "Option::deserialize")]
    pub reservation_expired_at: Option<i32>,
    /// شناسه منحصر به فرد سفارش در سیستم فروشنده
    #[serde(rename = "merchant_order_id")]
    pub merchant_order_id: String,
    #[serde(rename = "status")]
    pub status: models::OrderStatusEnum,
    #[serde(rename = "status_display")]
    pub status_display: String,
    /// مجموع قیمت اولیه تمام کالاهای سفارش بدون تخفیف (به تومان)
    #[serde(rename = "main_amount")]
    pub main_amount: i32,
    /// قیمت نهایی قابل پرداخت توسط مشتری: مبلغ_اصلی - مبلغ_تخفیف + مبلغ_مالیات (به تومان)
    #[serde(rename = "final_amount")]
    pub final_amount: i32,
    /// مبلغ کل پرداخت شده توسط کاربر: مبلغ_نهایی + هزینه_ارسال (به تومان)
    #[serde(rename = "total_paid_amount")]
    pub total_paid_amount: i32,
    /// مبلغ کل تخفیف اعمال شده بر سفارش (به تومان)
    #[serde(rename = "discount_amount")]
    pub discount_amount: i32,
    /// مبلغ کل مالیات برای سفارش (به تومان)
    #[serde(rename = "tax_amount")]
    pub tax_amount: i32,
    /// هزینه ارسال برای سفارش (به تومان)
    #[serde(rename = "shipping_amount")]
    pub shipping_amount: i32,
    /// مقدار تخفیف از برنامه باشگاه مشتریان/پاداش (به تومان)
    #[serde(rename = "loyalty_amount")]
    pub loyalty_amount: i32,
    /// آدرسی برای دریافت اطلاع رسانی وضعیت پرداخت پس از تکمیل سفارش
    #[serde(rename = "callback_url")]
    pub callback_url: String,
    #[serde(rename = "merchant")]
    pub merchant: Box<models::Merchant>,
    #[serde(rename = "items")]
    pub items: Vec<models::OrderItemCreate>,
    #[serde(rename = "source_address", deserialize_with = "Option::deserialize")]
    pub source_address: Option<serde_json::Value>,
    #[serde(rename = "destination_address", deserialize_with = "Option::deserialize")]
    pub destination_address: Option<serde_json::Value>,
    #[serde(rename = "selected_shipping_method")]
    pub selected_shipping_method: Box<models::ShippingMethod>,
    #[serde(rename = "shipping_selected_at", deserialize_with = "Option::deserialize")]
    pub shipping_selected_at: Option<String>,
    #[serde(rename = "address_selected_at", deserialize_with = "Option::deserialize")]
    pub address_selected_at: Option<String>,
    /// هزینه روش بسته‌بندی انتخاب‌شده (به تومان)
    #[serde(rename = "packing_amount")]
    pub packing_amount: i32,
    #[serde(rename = "packing_selected_at", deserialize_with = "Option::deserialize")]
    pub packing_selected_at: Option<String>,
    #[serde(rename = "selected_packing")]
    pub selected_packing: Box<models::Packing>,
    #[serde(rename = "can_select_packing")]
    pub can_select_packing: bool,
    #[serde(rename = "can_select_shipping")]
    pub can_select_shipping: bool,
    #[serde(rename = "can_select_address")]
    pub can_select_address: bool,
    #[serde(rename = "can_proceed_to_payment")]
    pub can_proceed_to_payment: bool,
    #[serde(rename = "is_paid")]
    pub is_paid: bool,
    #[serde(rename = "user")]
    pub user: Box<models::OrderUser>,
    #[serde(rename = "payment")]
    pub payment: Box<models::PaymentOrder>,
    /// Preparation time for the order (in days)
    #[serde(rename = "preparation_time")]
    pub preparation_time: i32,
    /// Total weight of the order (in grams)
    #[serde(rename = "weight")]
    pub weight: f64,
    #[serde(rename = "selected_shipping_data")]
    pub selected_shipping_data: std::collections::HashMap<String, serde_json::Value>,
    /// کد مرجع یکتا برای پیگیری سفارش مشتری (قالب: BD-XXXXXXXX)
    #[serde(rename = "reference_code")]
    pub reference_code: String,
    #[serde(rename = "promotion_discount_amount")]
    pub promotion_discount_amount: f64,
    #[serde(rename = "promotion_data")]
    pub promotion_data: std::collections::HashMap<String, serde_json::Value>,
    /// Markup amount for the order (in Tomans)
    #[serde(rename = "digipay_markup_amount")]
    pub digipay_markup_amount: i32,
    /// Markup commission percentage for the order (in percent)
    #[serde(rename = "markup_commission_percentage")]
    pub markup_commission_percentage: i32,
    #[serde(rename = "previous_status", deserialize_with = "Option::deserialize")]
    pub previous_status: Option<models::OrderStatusEnum>,
    #[serde(rename = "previous_status_display")]
    pub previous_status_display: String,
}

impl OrderDetail {
    pub fn new(id: i32, created_at: String, order_uuid: uuid::Uuid, reservation_expired_at: Option<i32>, merchant_order_id: String, status: models::OrderStatusEnum, status_display: String, main_amount: i32, final_amount: i32, total_paid_amount: i32, discount_amount: i32, tax_amount: i32, shipping_amount: i32, loyalty_amount: i32, callback_url: String, merchant: models::Merchant, items: Vec<models::OrderItemCreate>, source_address: Option<serde_json::Value>, destination_address: Option<serde_json::Value>, selected_shipping_method: models::ShippingMethod, shipping_selected_at: Option<String>, address_selected_at: Option<String>, packing_amount: i32, packing_selected_at: Option<String>, selected_packing: models::Packing, can_select_packing: bool, can_select_shipping: bool, can_select_address: bool, can_proceed_to_payment: bool, is_paid: bool, user: models::OrderUser, payment: models::PaymentOrder, preparation_time: i32, weight: f64, selected_shipping_data: std::collections::HashMap<String, serde_json::Value>, reference_code: String, promotion_discount_amount: f64, promotion_data: std::collections::HashMap<String, serde_json::Value>, digipay_markup_amount: i32, markup_commission_percentage: i32, previous_status: Option<models::OrderStatusEnum>, previous_status_display: String) -> OrderDetail {
        OrderDetail {
            id,
            created_at,
            order_uuid,
            reservation_expired_at,
            merchant_order_id,
            status,
            status_display,
            main_amount,
            final_amount,
            total_paid_amount,
            discount_amount,
            tax_amount,
            shipping_amount,
            loyalty_amount,
            callback_url,
            merchant: Box::new(merchant),
            items,
            source_address,
            destination_address,
            selected_shipping_method: Box::new(selected_shipping_method),
            shipping_selected_at,
            address_selected_at,
            packing_amount,
            packing_selected_at,
            selected_packing: Box::new(selected_packing),
            can_select_packing,
            can_select_shipping,
            can_select_address,
            can_proceed_to_payment,
            is_paid,
            user: Box::new(user),
            payment: Box::new(payment),
            preparation_time,
            weight,
            selected_shipping_data,
            reference_code,
            promotion_discount_amount,
            promotion_data,
            digipay_markup_amount,
            markup_commission_percentage,
            previous_status,
            previous_status_display,
        }
    }
}

