/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Packing {
    #[serde(rename = "id")]
    pub id: i32,
    /// نام روش/گزینه بسته‌بندی
    #[serde(rename = "name")]
    pub name: String,
    /// هزینه بسته بندی به تومان
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<i32>,
}

impl Packing {
    pub fn new(id: i32, name: String) -> Packing {
        Packing {
            id,
            name,
            price: None,
        }
    }
}

