/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentOrder {
    #[serde(rename = "final_amount")]
    pub final_amount: i32,
    #[serde(rename = "gateway_type")]
    pub gateway_type: models::GatewayTypeEnum,
    #[serde(rename = "gateway_type_display")]
    pub gateway_type_display: String,
    #[serde(rename = "paid_at")]
    pub paid_at: String,
    #[serde(rename = "gateway_name", deserialize_with = "Option::deserialize")]
    pub gateway_name: Option<String>,
    #[serde(rename = "invoice_id", deserialize_with = "Option::deserialize")]
    pub invoice_id: Option<String>,
    #[serde(rename = "settlement_date")]
    pub settlement_date: String,
    #[serde(rename = "settlement_status")]
    pub settlement_status: i32,
    #[serde(rename = "settlement_status_display")]
    pub settlement_status_display: String,
}

impl PaymentOrder {
    pub fn new(final_amount: i32, gateway_type: models::GatewayTypeEnum, gateway_type_display: String, paid_at: String, gateway_name: Option<String>, invoice_id: Option<String>, settlement_date: String, settlement_status: i32, settlement_status_display: String) -> PaymentOrder {
        PaymentOrder {
            final_amount,
            gateway_type,
            gateway_type_display,
            paid_at,
            gateway_name,
            invoice_id,
            settlement_date,
            settlement_status,
            settlement_status_display,
        }
    }
}

