/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RefundOrder : Serializer for refunding an order.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefundOrder {
    /// Optional reason for the refund
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl RefundOrder {
    /// Serializer for refunding an order.
    pub fn new() -> RefundOrder {
        RefundOrder {
            reason: None,
        }
    }
}

