/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReviveShipment {
    /// The preparation time for the order in days.
    #[serde(rename = "preparation_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub preparation_time: Option<Option<i32>>,
}

impl ReviveShipment {
    pub fn new() -> ReviveShipment {
        ReviveShipment {
            preparation_time: None,
        }
    }
}

