/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ShippingMethod : Serializer for shipping method details.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShippingMethod {
    #[serde(rename = "id")]
    pub id: i32,
    /// نام روش ارسال
    #[serde(rename = "name")]
    pub name: String,
    /// توضیحات روش ارسال و جزئیات تحویل آن
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// نوع روش ارسال: عادی یا دیجی اکسپرس  * `1` - سایر * `2` - دیجی اکسپرس
    #[serde(rename = "shipping_type", skip_serializing_if = "Option::is_none")]
    pub shipping_type: Option<models::ShippingTypeEnum>,
    #[serde(rename = "get_shipping_type_display")]
    pub get_shipping_type_display: String,
    #[serde(rename = "shipping_type_display")]
    pub shipping_type_display: String,
    /// هزینه ارسال برای منطقه اولیه (مثلاً تهران) به تومان
    #[serde(rename = "cost", skip_serializing_if = "Option::is_none")]
    pub cost: Option<i32>,
    /// هزینه ارسال برای مناطق دیگر به تومان
    #[serde(rename = "secondary_cost", skip_serializing_if = "Option::is_none")]
    pub secondary_cost: Option<i32>,
    /// حداقل تعداد روزها از تاریخ سفارش تا تحویل
    #[serde(rename = "minimum_time_sending", skip_serializing_if = "Option::is_none")]
    pub minimum_time_sending: Option<i32>,
    /// حداکثر تعداد روزها از تاریخ سفارش تا تحویل
    #[serde(rename = "maximum_time_sending", skip_serializing_if = "Option::is_none")]
    pub maximum_time_sending: Option<i32>,
    #[serde(rename = "delivery_time_display")]
    pub delivery_time_display: String,
    #[serde(rename = "delivery_time_range_display")]
    pub delivery_time_range_display: Box<models::DeliveryTimeRangeDisplay>,
    #[serde(rename = "inventory_address")]
    pub inventory_address: Box<models::BusinessAddress>,
    /// Whether the shipping method is pay at destination
    #[serde(rename = "is_pay_at_destination", skip_serializing_if = "Option::is_none")]
    pub is_pay_at_destination: Option<bool>,
}

impl ShippingMethod {
    /// Serializer for shipping method details.
    pub fn new(id: i32, name: String, get_shipping_type_display: String, shipping_type_display: String, delivery_time_display: String, delivery_time_range_display: models::DeliveryTimeRangeDisplay, inventory_address: models::BusinessAddress) -> ShippingMethod {
        ShippingMethod {
            id,
            name,
            description: None,
            shipping_type: None,
            get_shipping_type_display,
            shipping_type_display,
            cost: None,
            secondary_cost: None,
            minimum_time_sending: None,
            maximum_time_sending: None,
            delivery_time_display,
            delivery_time_range_display: Box::new(delivery_time_range_display),
            inventory_address: Box::new(inventory_address),
            is_pay_at_destination: None,
        }
    }
}

