/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TypeNameEnum : * `color` - رنگ * `size` - اندازه * `warranty` - گارانتی * `weight` - وزن * `other` - سایر
/// * `color` - رنگ * `size` - اندازه * `warranty` - گارانتی * `weight` - وزن * `other` - سایر
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeNameEnum {
    #[serde(rename = "color")]
    Color,
    #[serde(rename = "size")]
    Size,
    #[serde(rename = "warranty")]
    Warranty,
    #[serde(rename = "weight")]
    Weight,
    #[serde(rename = "other")]
    Other,

}

impl std::fmt::Display for TypeNameEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Color => write!(f, "color"),
            Self::Size => write!(f, "size"),
            Self::Warranty => write!(f, "warranty"),
            Self::Weight => write!(f, "weight"),
            Self::Other => write!(f, "other"),
        }
    }
}

impl Default for TypeNameEnum {
    fn default() -> TypeNameEnum {
        Self::Color
    }
}

