/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WalletBalance {
    /// Current wallet balance in Tomans
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<i32>,
    /// Deadline for settling negative balance
    #[serde(rename = "negative_settlement_deadline", deserialize_with = "Option::deserialize")]
    pub negative_settlement_deadline: Option<String>,
}

impl WalletBalance {
    pub fn new(negative_settlement_deadline: Option<String>) -> WalletBalance {
        WalletBalance {
            amount: None,
            negative_settlement_deadline,
        }
    }
}

